title: Sasank's Blog
description: >
  Code. Books. Languages.
baseurl: "https://chsasank.github.io/"
url: "/"
paginate:	2 # The number of posts to show per page on your homepage
name: "Sasank Chilamkurthy"
email: 'sasankchilamkurthy@gmail.com'
markdown: kramdown
permalink: none
kramdown:
  parse_block_html: true
gems:
  - jekyll-paginate
  - jekyll-compose
  - jekyll-sass-converter
  - jekyll-textile-converter
